// Builds src/styles/cursors.css.
// Run: npm run cursors
//
// The cursors are real CSS cursors, not a div chasing the mouse, so they move
// at the speed of the system cursor. The SVGs are inlined as data URIs (no
// extra request), with a 2x variant so they stay sharp on Retina screens.
import { writeFileSync } from "node:fs";

const PAPER = "#f4f2ed";
const INK = "#14130f";
const SIGNAL = "#ff6a4d";

// A smooth arrow, roughly the size of the macOS default cursor.
const WIDTH = 15;
const HEIGHT = 21;
const ARROW = "M2.2 1.6v15.9l3.9-3.7 2.6 5.8 2.7-1.2-2.6-5.7h5.4z";

function svg(fill, stroke, scale) {
  return (
    `<svg xmlns='http://www.w3.org/2000/svg' width='${WIDTH * scale}' height='${HEIGHT * scale}' viewBox='0 0 16 22'>` +
    `<path d='${ARROW}' fill='${fill}' stroke='${stroke}' stroke-width='1.6' stroke-linejoin='round'/>` +
    `</svg>`
  );
}

// Only the characters that break a CSS url() or a data URI get escaped.
const uri = (s) => `url("data:image/svg+xml,${s.replace(/#/g, "%23").replace(/</g, "%3C").replace(/>/g, "%3E")}")`;

function cursor(fill, stroke, fallback) {
  const one = uri(svg(fill, stroke, 1));
  const two = uri(svg(fill, stroke, 2));
  // Hotspot is the arrow tip.
  return [
    `cursor: ${one} 2 1, ${fallback};`,
    `cursor: image-set(${one} 1x, ${two} 2x) 2 1, ${fallback};`,
  ];
}

const indent = (lines, n) => lines.map((line) => " ".repeat(n) + line).join("\n");

const css = `/* Generated by tools/cursors/build.mjs. Do not edit by hand. */

/* Custom cursors for mouse and trackpad only; touch screens keep theirs.
   Ink arrow everywhere, the same arrow in signal red on anything clickable.
   Text fields keep the system I-beam so typing feels normal. */
@media (hover: hover) and (pointer: fine) {
  html {
${indent(cursor(INK, PAPER, "auto"), 4)}
  }

  a,
  button,
  summary,
  label[for],
  select,
  [role="button"],
  [data-egg],
  .hero-train {
${indent(cursor(SIGNAL, INK, "pointer"), 4)}
  }

  input:not([type="submit"]):not([type="button"]),
  textarea,
  [contenteditable] {
    cursor: text;
  }

  button:disabled {
    cursor: not-allowed;
  }
}
`;

writeFileSync(new URL("../../src/styles/cursors.css", import.meta.url), css);
console.log(`cursors.css written (${css.length} bytes)`);
